# base image
FROM node:14-alpine

# set working directory
WORKDIR /app

# copy package.json and package-lock.json
COPY package*.json ./

# install dependencies
RUN npm install

# copy app files
COPY . .

# build app
RUN npm run build

# set environment variable
ENV NODE_ENV=production

# start app

CMD ["npm", "run", "dev"]
