version: "3"
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - express-be
      - rails-be # add this line
    networks:
      - my-network

  express-be:
    build:
      context: ./backends/express-be
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - my-network

  rails-be:
    build:
      context: ./backends/rails-be
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
