version: "3.9"

services:
  rails:
    build: ./railic
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3001:3000"
    networks:
      - backend

  express:
    build: ./expressive
    command: npm start
    ports:
      - "1111:7777"
    networks:
      - backend
networks:
  backend:
